services:
  db:
    image: postgres:latest
    container_name: bms_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - bms_network

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: bms_mosquitto_broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    networks:
      - bms_network


  backend:
    build: ./backend
    container_name: bms_backend
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - db
      - mosquitto
      - fake-ai
    networks:
      - bms_network

  frontend:
    build: ./frontend
    container_name: bms_frontend
    env_file:
      - .env
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - bms_network

  publisher:
    build: ./data-publisher
    container_name: bms_data_publisher
    env_file:
      - .env
    volumes:
      - ./csv-data:/data:ro
    depends_on:
      - mosquitto
    networks:
      - bms_network

  fake-ai:
    build:
      context: ./fake-ai
    container_name: bms_fake_ai
    env_file:
      - .env
    ports:
      - "8001:8001"
    networks:
      - bms_network
volumes:
  postgres_data: 

networks:
  bms_network: