services:
  db:
    image: postgres:latest
    container_name: bms_db
    environment:
      POSTGRES_USER: mqzesh
      POSTGRES_PASSWORD: mqzesh
      POSTGRES_DB: bms_database
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - bms_network

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: bms_mosquitto_broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    networks:
      - bms_network


  backend:
    build: ./backend
    container_name: bms_backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: mqzesh
      DB_PASSWORD: mqzesh
      DB_NAME: bms_database
      PORT: 3001
      JWT_SECRET: 23FbL8enMBFCAo5ucG7dPQhHzmvtTZmLnUq5eUe67hRzm9Iqyr
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
    ports:
      - "3001:3001"
    depends_on:
      - db
      - mosquitto
    networks:
      - bms_network

  publisher:
    build: ./data-publisher
    container_name: bms_data_publisher
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
      MQTT_TOPIC: sensor/data
      CSV_FILE: /data/data.csv
      TIMESLEEP: 5
    volumes:
      - ./csv-data:/data:ro
    depends_on:
      - mosquitto
    networks:
      - bms_network

volumes:
  postgres_data: 

networks:
  bms_network: