CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS timestamp_ (
    id SERIAL PRIMARY KEY,
    reading_timestamp TIMESTAMP NOT NULL,
    ai_soc DECIMAL(5, 2) NOT NULL,
    sensor_soc DECIMAL(5, 2) NOT NULL
);